image: docker:latest

stages:
  - run_docker_compose

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

run_docker_compose:
  stage: run_docker_compose
  script:
    - apk add --no-cache curl py-pip
    - pip install docker-compose
    - mkdir testResults
    - mkdir testResults/API
    - mkdir testResults/UI
    - docker-compose up -d
    - docker-compose exec -T app mvn test
    - docker-compose down -v
  artifacts:
    paths:
      - testResults/
    expire_in: 30 days