image: docker:latest

stages:
  - run_docker_compose

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  - apk update
  - apk upgrade
  - apk add python python-dev py-pip build-base
  - apk add --update curl && \
    rm -rf /var/cache/apk/*
  - curl -L https://github.com/docker/compose/releases/download/1.8.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose
  - pip install docker-compose

run_docker_compose:
  stage: run_docker_compose
  script:
#    - apk add --update python python-dev py-pip build-base      # <--
#    - pip install docker-compose     # <--
    - docker-compose up -d
    - mkdir testResults
    - mkdir testResults/API
    - mkdir testResults/UI
    - docker-compose up -d
    - docker-compose exec -T app mvn test
    - docker-compose down -v
  artifacts:
    paths:
      - testResults/
    expire_in: 30 days