image: docker:latest

stages:
  - run_docker_compose

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

run_docker_compose:
  stage: run_docker_compose
  script:
    - apk add py-pip
    - apk add python-dev libffi-dev openssl-dev gcc libc-dev make
    - pip install docker-compose

    - mkdir testResults
    - mkdir testResults/API
    - mkdir testResults/UI
    - docker-compose up -d
    - docker-compose exec -T app mvn test -DsuiteXmlFile=testrunner.xml
    - docker-compose down -v
  artifacts:
    paths:
      - testResults/
    expire_in: 30 days