api:
  hello-world-url: hello
  remote-environment: crossbrowsertesting.com/api/v3/selenium
web:
  homepage-url: http://awful-valentine.com/
  admin-username: srini.reddy@bcgdv.com
  admin-password: Superdogs@321
testAutomation:
  data:
    web:
      login1-email: login@login.com
      login1-password: password
    crossbrowsertesting:
      username: username
      authkey: authkey
    browserstack:
      username: srinireddy1
      authkey: FMaNG1ZZDqShMxdFxKzq
---
spring:
  profiles: DEV
api:
  base-url: http://awful-valentine.com/
#
---
spring:
  profiles: QA
api:
  base-url: http://awful-valentine.com/
#  http://awful-valentine.com/

---
spring:
  profiles: STAGE
api:
  base-url: http://awful-valentine.com/
#  http://awful-valentine.com/